### ISSUE TITLE
Feedback to your Tribute Page exercise

### ISSUE THREAD

**Issue by carmen-tm** [MichaelChernyshov/tribute-page#1]
Hi, Mikhail!

I just had a look at your Tribute Page in detail and looks great, well done!! :) I have opened this "_issue_" here on your GitHub repository to give you some feedback as I promised. *Issues* are used to do many things, for example, to keep track of small tasks, bugs, enhancements or any other requests. Here you have some [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) about them. As a developer, you are going to use them a lot in the future, so I thought it would be a good idea to communicate my feedback through one 🚀.

You could _reply_ to this issue with a message through the GitHub interface if you want to, and _close_ it when you think all the fixes are ready. I usually open issues on my repositories as personal notes listing all the things that I want to improve in the future, describing them, etc. so I don't forget :)

So about the feedback:
- Great that you have picked your **own topic** for this exercise (and such an important one... I have struggled a lot with anxiety in the past... so thanks for the bits of advice on that!).
- Great **design** too 👍 
- So cool that you have **published** your [page](https://michaelchernyshov.github.io/tribute-page/) too.
- Cool that you have added a **repo description** through a _Readme.md_ file 🚀
- **Semantics** is not bad, but I think you are aware that it could be improved still :)
- **Indentation** is perfect, well done 👏🏻. Clear structure, very easy to understand at first glance by an external developer who didn't code it (myself in this case). Nice! 
- Great that you linked the CSS style file too. I know from class that you already know quite a lot of CSS, so I'm sure that you will enjoy the next modules :D

Just some small improvements I found:
- [x] Maybe is a good idea to put the [link to your website](https://michaelchernyshov.github.io/tribute-page/) in your repository details, as well as the Description and some Tags (for example: HTML, CSS)
- [x] Your _Readme.md_ file has .md extension means that it's a Markdown file, not a HMTL one, so it has its own syntax. Actually, is the same syntax that GitHub issues use, so I'm using it in this message. Instead of creating a `<h1>Heading</h1>` you write `#Heading`. You can find [more info and documentation here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). So it would be great if you format your text there in Markdown instead of in HTML 😉
- [x] Pick a better `title` to your page? "Document" seems too generic hehe.
- [x] Improve semantics. Review your general structure: Should the `main` tag wrap everything...? Don't u miss a proper `header`? What about a `footer`?
- [x] More semantics: Review your `img` tag. Well done with the `figcaption`, but don't u miss something there? [See some documentation](https://www.w3schools.com/tags/tag_figcaption.asp)

You could fix these 5 small things, and after that close this issue when it's ready. Once again, well done. Congratulations!! A lot more to come!

**Comment by MichaelChernyshov** [comment]
Hello, thanks for feedback it was so glad to read all. I've improved all and checked the tasks, so you can look forward commits.

**Comment by carmen-tm** [comment]
I just saw your commit and...

![perfect](https://user-images.githubusercontent.com/7012771/210057846-636578f2-3c02-4f21-91d8-1ec7fc0a2363.gif)

Well done! 😎
